# -*- coding: utf-8 -*-
# Generated by Django 1.11.12 on 2018-12-20 09:35
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CompanayAroundEnvironment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('facilitesName', models.CharField(max_length=100)),
                ('facilitesNumber', models.IntegerField()),
                ('oneFacilitesMemberMaxNum', models.IntegerField()),
                ('oneFacilitesMinTimeCell', models.IntegerField()),
                ('priceForOneTimeCell', models.IntegerField()),
                ('serviceStart', models.PositiveSmallIntegerField()),
                ('serviceEnd', models.PositiveSmallIntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='CompanyAccounts',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tid', models.CharField(max_length=100)),
                ('password', models.CharField(max_length=100)),
                ('authority', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='CompanyAddress',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('address1', models.CharField(max_length=100)),
                ('address2', models.CharField(max_length=100)),
                ('address3', models.CharField(max_length=100)),
                ('address4', models.CharField(max_length=100)),
                ('address5', models.CharField(max_length=100)),
                ('address5_1', models.CharField(max_length=100)),
                ('address6', models.CharField(max_length=100)),
                ('address6_1', models.CharField(max_length=100)),
                ('address7', models.CharField(max_length=100)),
                ('address8', models.CharField(max_length=100)),
                ('addressLatitude', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='CompanyAroundFacilites',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('facilitesName', models.CharField(max_length=100)),
                ('facilitesExplain', models.TextField(max_length=100000)),
                ('timeForWalk', models.PositiveSmallIntegerField()),
                ('timeForCar', models.PositiveSmallIntegerField()),
                ('serviceStart', models.PositiveSmallIntegerField()),
                ('serviceEnd', models.PositiveSmallIntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='CompanyAuxiliaryFacilites',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('facilitesName', models.CharField(max_length=100)),
                ('facilitesNumber', models.PositiveSmallIntegerField()),
                ('oneFacilitesMemberMaxNum', models.PositiveSmallIntegerField()),
                ('oneFacilitesMinTimeCell', models.PositiveSmallIntegerField()),
                ('priceForOneTimeCell', models.IntegerField()),
                ('serviceStart', models.PositiveSmallIntegerField()),
                ('serviceEnd', models.PositiveSmallIntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='CompanyInfomations',
            fields=[
                ('identifyCode', models.CharField(max_length=100, primary_key=True, serialize=False, unique=True)),
                ('hotelName', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='CompanyInnerRoomFacilites',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('facilitesName', models.CharField(max_length=100)),
                ('oneFacilitesMemberMaxNum', models.IntegerField()),
                ('companyInfo_InnerRoomFacilitesFK', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='fatogo_RDB.CompanyInfomations')),
            ],
        ),
        migrations.CreateModel(
            name='CompanyMasterInfomations',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('masterName', models.CharField(max_length=100)),
                ('masterRegistrationNumber', models.CharField(max_length=100)),
                ('masterBusinessLicenseNumber', models.CharField(max_length=100)),
                ('masterPhoneNumber', models.CharField(max_length=100)),
                ('masterEmail', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='UserInfo',
            fields=[
                ('kakaoTalkID', models.CharField(max_length=100, primary_key=True, serialize=False)),
                ('tripPerpose', models.CharField(max_length=100)),
                ('organizationName', models.CharField(max_length=100)),
                ('startingAreaSI', models.CharField(max_length=100)),
                ('startingAreaGUUN', models.CharField(max_length=100)),
                ('startingAreaGU', models.CharField(max_length=100)),
                ('desiredTripAreaSI', models.CharField(max_length=100)),
                ('desiredTripAreaGUUN', models.CharField(max_length=100)),
                ('desiredTripAreaGU', models.CharField(max_length=100)),
                ('expectMemberNumber', models.PositiveSmallIntegerField()),
                ('desiredAuxiliaryFacilites', models.CharField(max_length=100)),
                ('desiredInnerFacilites', models.CharField(max_length=100)),
                ('desiredAroundFacilites', models.CharField(max_length=100)),
                ('desiredAroundEnvironment', models.CharField(max_length=100)),
            ],
        ),
        migrations.AddField(
            model_name='companyauxiliaryfacilites',
            name='companyInfo_AuxiliaryFacilitesFK',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='fatogo_RDB.CompanyInfomations'),
        ),
        migrations.AddField(
            model_name='companyaroundfacilites',
            name='companyInfo_AroundFacilitesFK',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='fatogo_RDB.CompanyInfomations'),
        ),
        migrations.AddField(
            model_name='companyaddress',
            name='companyInfo_AddressFK',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='fatogo_RDB.CompanyInfomations'),
        ),
        migrations.AddField(
            model_name='companyaccounts',
            name='companyInfo_AccountsFK',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='fatogo_RDB.CompanyInfomations'),
        ),
        migrations.AddField(
            model_name='companayaroundenvironment',
            name='companyInfo_AroundEnvironmentFK',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='fatogo_RDB.CompanyInfomations'),
        ),
    ]
