# -*- coding: utf-8 -*-
# Generated by Django 1.11.12 on 2018-12-20 19:47
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fatogo_RDB', '0003_auto_20181220_1333'),
    ]

    operations = [
        migrations.AddField(
            model_name='companyinfomations',
            name='hotelTraffic',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='companyinfomations',
            name='hotelavgScore',
            field=models.CharField(default='testasdas', max_length=3),
        ),
    ]
