# -*- coding: utf-8 -*-
# Generated by Django 1.11.12 on 2018-12-22 04:16
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fatogo_RDB', '0007_auto_20181221_2252'),
    ]

    operations = [
        migrations.AddField(
            model_name='companyaddress',
            name='addressLongitude',
            field=models.CharField(default='testasdas', max_length=100),
        ),
    ]
