# -*- coding: utf-8 -*-
# Generated by Django 1.11.12 on 2018-12-30 06:45
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fatogo_RDB', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='companyaddress',
            name='address1',
            field=models.CharField(blank=True, default='testasdas', max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='companyreview',
            name='reviewedGroup',
            field=models.CharField(default='te stasdas', max_length=100),
        ),
    ]
