# -*- coding: utf-8 -*-
# Generated by Django 1.11.12 on 2018-12-21 22:52
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('fatogo_RDB', '0006_auto_20181221_2243'),
    ]

    operations = [
        migrations.RenameField(
            model_name='companyreview',
            old_name='companyInfo_AroundEnvironmentFK',
            new_name='companyInfo_ReviewFK',
        ),
    ]
