# -*- coding: utf-8 -*-
# Generated by Django 1.11.12 on 2018-12-25 14:19
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fatogo_RDB', '0009_companymasterinfomations_companyinfo_companymasterinfomationsfk'),
    ]

    operations = [
        migrations.AddField(
            model_name='companyinfomations',
            name='hotelTotalReivew',
            field=models.PositiveSmallIntegerField(default=0),
        ),
    ]
