# -*- coding: utf-8 -*-
# Generated by Django 1.11.12 on 2018-12-27 09:07
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('fatogo_RDB', '0011_auto_20181225_1424'),
    ]

    operations = [
        migrations.CreateModel(
            name='CompanyRoomTypeInfomations',
            fields=[
                ('roomType', models.CharField(default='testasdas', max_length=100, primary_key=True, serialize=False, unique=True)),
                ('roomWidth', models.PositiveSmallIntegerField(default=0)),
                ('roomHeight', models.PositiveSmallIntegerField(default=0)),
                ('roomPrice', models.IntegerField(default=0)),
                ('roomMaxHumanNum', models.IntegerField(default=3)),
                ('roomAvgHumanNum', models.IntegerField(default=1)),
            ],
        ),
        migrations.RenameField(
            model_name='companyinnerroomfacilites',
            old_name='companyInfo_InnerRoomFacilitesFK',
            new_name='companyInfo_companyRoomFacilitesFK',
        ),
        migrations.AddField(
            model_name='companyinfomations',
            name='hotelCheckin',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='companyinfomations',
            name='hotelCheckout',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='companyroomtypeinfomations',
            name='companyInfo_RoomTypeInfomationsFK',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='fatogo_RDB.CompanyInfomations'),
        ),
        migrations.AddField(
            model_name='companyinnerroomfacilites',
            name='companyRoomTypeInfomations_InnerRoomFacilitesFK',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='fatogo_RDB.CompanyRoomTypeInfomations'),
            preserve_default=False,
        ),
    ]
